#pragma once

#define CHAPTER_ASSET(x) (x)

enum chapter_assets_index {
	PLIST_0,

	PLIST_MAPASSET1_IMG1,
	PLIST_MAPASSET1_IMG2,
	PLIST_MAPASSET1_PAL,
	PLIST_MAPASSET1_TSA_CONF,
	PLIST_CH0_MAP,
	PLIST_MAPASSET1_IMGANIM,

	PLIST_CH0_MAPCHG,
	PLIST_CH0_EVENT,
	PLIST_CH0_EVENTWM,

	PLIST_CH1_MAP,
	PLIST_CH1_MAPCHG,
	PLIST_CH1_EVENT,
	PLIST_CH1_EVENTWM,

	PLIST_CH2_MAP,
	PLIST_CH2_MAPCHG,
	PLIST_CH2_EVENT,
	PLIST_CH2_EVENTWM,

	PLIST_MAPASSET2_IMG,
	PLIST_MAPASSET2_PAL,
	PLIST_MAPASSET2_TSA_CONF,

	PLIST_CH3_MAP,
	PLIST_CH3_MAPCHG,
	PLIST_CH3_EVENT,
	PLIST_CH3_EVENTWM,

	PLIST_CH4_MAP,
	PLIST_CH4_MAPCHG,
	PLIST_CH4_EVENT,
	PLIST_CH4_EVENTWM,

	PLIST_CH5_MAP,
	PLIST_CH5_MAPCHG,
	PLIST_CH5_EVENT,
	PLIST_CH5_EVENTWM,

	PLIST_MAPASSET3_IMG,
	PLIST_MAPASSET3_PAL,
	PLIST_MAPASSET3_TSA_CONF,

	PLIST_CH6_MAP,
	PLIST_CH6_MAPCHG,
	PLIST_CH6_EVENT,
	PLIST_CH6_EVENTWM,

	PLIST_CH7_MAP,
	PLIST_CH7_MAPCHG,
	PLIST_CH7_EVENT,
	PLIST_CH7_EVENTWM,

	PLIST_MAPASSET4_IMG,
	PLIST_MAPASSET4_PAL,
	PLIST_MAPASSET4_TSA_CONF,

	PLIST_CH8_MAP,
	PLIST_CH8_MAPCHG,
	PLIST_CH8_EVENT,
	PLIST_CH8_EVENTWM,

	PLIST_MAPASSET5_IMG,
	PLIST_MAPASSET5_PAL,
	PLIST_MAPASSET5_TSA_CONF,

	PLIST_CH9_MAP,
	PLIST_CH9_MAPCHG,
	PLIST_CH9_EVENT,
	PLIST_CH9_EVENTWM,

	PLIST_CH10A_MAP,
	PLIST_CH10A_MAPCHG,
	PLIST_CH10A_EVENT,
	PLIST_CH10A_EVENTWM,

	PLIST_MAPASSET6_IMG,
	PLIST_MAPASSET6_PAL,
	PLIST_MAPASSET6_TSA_CONF,

	PLIST_CH11A_MAP,
	PLIST_CH11A_MAPCHG,
	PLIST_CH11A_EVENT,
	PLIST_CH11A_EVENTWM,

	PLIST_MAPASSET7_IMG,
	PLIST_MAPASSET7_PAL,
	PLIST_MAPASSET7_TSA_CONF,

	PLIST_CH12_MAP,
	PLIST_CH12_MAPCHG,
	PLIST_CH12_EVENT,
	PLIST_CH12_EVENTWM,

	PLIST_MAPASSET1B_IMG2,
	PLIST_MAPASSET1B_PAL,
	PLIST_MAPASSET1B_TSA_CONF,

	PLIST_CH13_MAP,
	PLIST_CH13_MAPCHG,
	PLIST_CH13_EVENT,
	PLIST_CH13_EVENTWM,

	PLIST_MAPASSET8_IMG,
	PLIST_MAPASSET8_PAL,
	PLIST_MAPASSET8_TSA_CONF,

	PLIST_CH14_MAP,
	PLIST_CH14_EVENT,
	PLIST_CH14_EVENTWM,

	PLIST_CH15_MAP,
	PLIST_CH15_MAPCHG,
	PLIST_CH15_EVENT,
	PLIST_CH15_EVENTWM,

	PLIST_MAPASSET4B_PAL,

	PLIST_CH16_MAP,
	PLIST_CH16_MAPCHG,
	PLIST_CH16_EVENT,
	PLIST_CH16_EVENTWM,

	PLIST_CH17C_MAP,
	PLIST_CH17C_MAPCHG,
	PLIST_CH17C_EVENT,
	PLIST_CH17C_EVENTWM,

	PLIST_MAPASSET9_IMG,
	PLIST_MAPASSET9_PAL,
	PLIST_MAPASSET9_TSA_CONF,
	PLIST_CH18C_MAP,
	PLIST_MAPASSET9_IMGANIM,
	PLIST_MAPASSET9_PALANIM,

	PLIST_CH18C_MAPCHG,
	PLIST_CH18C_EVENT,
	PLIST_CH18C_EVENTWM,

	PLIST_CH19C_MAP,
	PLIST_CH19C_MAPCHG,
	PLIST_CH19C_EVENT,
	PLIST_CH19C_EVENTWM,

	PLIST_MAPASSET10_IMG,
	PLIST_MAPASSET10_PAL,
	PLIST_MAPASSET10_TSA_CONF,

	PLIST_CH20C_MAP,
	PLIST_CH20C_MAPCHG,
	PLIST_CH20C_EVENT,
	PLIST_CH20C_EVENTWM,

	PLIST_MAPASSET01C_IMG,
	PLIST_MAPASSET01C_PAL,
	PLIST_MAPASSET01C_TSA_CONF,

	PLIST_CH21_MAP,
	PLIST_CH21_MAPCHG,
	PLIST_CH21_EVENT,
	PLIST_CH21_EVENTWM,

	PLIST_MAPASSET11_IMG,
	PLIST_MAPASSET11_PAL,
	PLIST_MAPASSET11_TSA_CONF,
	PLIST_CH22_MAP,
	PLIST_MAPASSET11_IMGANIM,
	PLIST_MAPASSET11_PALANIM,

	PLIST_CH22_MAPCHG,
	PLIST_CH22_EVENT,
	PLIST_CH22_EVENTWM,

	PLIST_CH23_MAP,
	PLIST_CH23_MAPCHG,
	PLIST_CH23_EVENT,
	PLIST_CH23_EVENTWM,

	PLIST_MAPASSET12_IMG,
	PLIST_MAPASSET12_PAL,
	PLIST_MAPASSET12_TSA_CONF,

	PLIST_CH24_MAP,
	PLIST_CH24_MAPCHG,
	PLIST_CH24_EVENT,
	PLIST_CH24_EVENTWM,

	PLIST_CH25_MAP,
	PLIST_MAPASSET12_PALANIM,
	PLIST_CH25_EVENT,

	PLIST_CH10B_MAP,
	PLIST_CH10B_MAPCHG,
	PLIST_CH10B_EVENT,
	PLIST_CH10B_EVENTWM,

	PLIST_CH11B_MAP,
	PLIST_CH11B_MAPCHG,
	PLIST_CH11B_EVENT,
	PLIST_CH11B_EVENTWM,

	PLIST_MAPASSET1_PAL_NIGHT,

	PLIST_CH17D_MAP,
	PLIST_CH17D_MAPCHG,
	PLIST_CH17D_EVENT,
	PLIST_CH17D_EVENTWM,

	PLIST_MAPASSET13_IMG,
	PLIST_MAPASSET13_PAL,
	PLIST_MAPASSET13_TSA_CONF,

	PLIST_CH18D_MAP,
	PLIST_CH18D_EVENT,
	PLIST_CH18D_EVENTWM,

	PLIST_MAPASSET13B_PAL,
	PLIST_MAPASSET13B_TSA_CONF,

	PLIST_CH19D_MAP,
	PLIST_CH19D_MAPCHG,
	PLIST_CH19D_EVENT,
	PLIST_CH19D_EVENTWM,

	PLIST_MAPASSET14_IMG,
	PLIST_MAPASSET14_PAL,
	PLIST_MAPASSET14_TSA_CONF,

	PLIST_CH20D_MAP,
	PLIST_CH20D_MAPCHG,
	PLIST_CH20D_EVENT,
	PLIST_CH20D_EVENTWM,

	PLIST_MAPASSET7B_PAL,
	PLIST_CH8X_MAP,
	PLIST_MAPASSET7B_PALANIM,
	PLIST_CH8X_EVENT,
	PLIST_CH8X_EVENTWM,

	PLIST_MAPASSET8B_PAL,
	PLIST_MAPASSET8B_TSA_CONF,

	PLIST_CH12X_MAP,
	PLIST_CH12X_MAPCHG,
	PLIST_CH12X_EVENT,
	PLIST_CH12X_EVENTWM,

	PLIST_MAPASSET4C_PAL,
	PLIST_CH14X_MAP,
	PLIST_MAPASSET4C_IMGANIM,
	PLIST_CH14X_MAPCHG,
	PLIST_CH14X_EVENT,
	PLIST_CH14X_EVENTWM,

	PLIST_MAPASSET12B_PAL,
	PLIST_CH16X_MAP,
	PLIST_CH16X_EVENT,
	PLIST_CH16X_EVENTWM,

	PLIST_MAPASSET10B_PAL,

	PLIST_CH20CX_MAP,
	PLIST_CH20CX_MAPCHG,
	PLIST_CH20CX_EVENT,
	PLIST_CH20CX_EVENTWM,

	PLIST_CH20DX_MAP,
	PLIST_CH20DX_EVENT,
	PLIST_CH20DX_EVENTWM,

	PLIST_MAPASSET4D_IMGANIM,

	PLIST_CH21X_MAP,
	PLIST_CH21X_MAPCHG,
	PLIST_CH21X_EVENT,
	PLIST_CH21X_EVENTWM,

	PLIST_MULTIARENA_MAP,

	PLIST_XMAP1_MAP,
	PLIST_XMAP1_EVENT,

	PLIST_XMAP2_MAP,
	PLIST_XMAP2_EVENT,

	PLIST_XMAP3_MAP,
	PLIST_XMAP3_EVENT,

	PLIST_XMAP4_MAP,
	PLIST_XMAP4_EVENT,

	PLIST_XMAP5_MAP,
	PLIST_XMAP5_EVENT,
};
