#pragma once

#define CHAPTER_ASSET(x) (x)

enum chapter_assets_index {
	PLIST_0,

	PLIST_MAPASSET1_IMG1,
	PLIST_MAPASSET1_IMG2,
	PLIST_MAPASSET1_PAL,
	PLIST_MAPASSET1_TSA_CONF,
	PLIST_CH0_MAP,
	PLIST_MAPASSET1_IMGANIM,
	PLIST_CH0_MAPCHG,
	PLIST_CH0_EVENT,
	PLIST_CH0_EVENTWM,

	PLIST_CH1_MAP,
	PLIST_CH1_MAPCHG,
	PLIST_CH1_EVENT,
	PLIST_CH1_EVENTWM,

	PLIST_CH2_MAP,
	PLIST_CH2_MAPCHG,
	PLIST_CH2_EVENT,
	PLIST_CH2_EVENTWM,

	PLIST_MAPASSET2_IMG1,
	PLIST_MAPASSET2_PAL,
	PLIST_MAPASSET2_TSA_CONF,

	PLIST_CH3_MAP,
	PLIST_CH3_MAPCHG,
	PLIST_CH3_EVENT,
	PLIST_CH3_EVENTWM,
};
