#include "prelude.h"
#include "eventinfo.h"

#include "constants/pids.h"
#include "constants/chapters.h"
#include "constants/msg.h"
#include "constants/flags.h"

struct BattleTalkEnt CONST_DATA gBattleTalkList[] = {
	{
		.pid = PID_CHAPTER1_4A,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_00E,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_CHAPTER2_4B,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_05C,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_4C,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_06C,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_4D,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_07E,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_4E,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_08A,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_4F,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_093,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_50,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_0AF,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_51,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_0BB,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_B5,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_BD5,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_52,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_0D7,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_53,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_0E8,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_56,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_100,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_58,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_111,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_B8,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_BDB,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_55,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_131,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_5A,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_140,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_B9,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_BE1,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_5D,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_151,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_NARCIAN,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_16F,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_C6,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_BE9,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_5E,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_181,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_5F,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_191,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_60,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_19D,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_61,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_1AB,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_BA,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_BF3,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_MURDOCK,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_1BD,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_ZEPHIEL,
		.chapter = CHAPTER_22,
		.msg = MSG_1CB,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_BRUNNYA,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_1F3,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_JAHN,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_1FD,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_68,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_966,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_C8,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_976,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_69,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_990,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_6A,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_99E,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_BORS_TUTORIAL,
		.chapter = CHAPTER_TUTORIAL,
		.msg = MSG_04B,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_C4,
		.chapter = CHAPTER_21X,
		.msg = MSG_C04,
		.flag = EVT_FLAG(1),
		.unk_0C = 0
	},
	{}
};

struct BattleTalkExtEnt CONST_DATA gBattleTalkExtList[] = {
	{
		.pid_a = PID_NARCIAN,
		.pid_b = PID_CLARINE,
		.chapter = CHAPTER_16,
		.msg = MSG_2A5,
		.flag = EVT_FLAG(19),
	},
	{
		.pid_a = PID_NARCIAN,
		.pid_b = PID_MELADY,
		.chapter = CHAPTER_16,
		.msg = MSG_2A6,
		.flag = EVT_FLAG(20),
	},
	{
		.pid_a = PID_NARCIAN,
		.pid_b = PID_ZEISS,
		.chapter = CHAPTER_16,
		.msg = MSG_2A7,
		.flag = EVT_FLAG(21),
	},
	{
		.pid_a = PID_NARCIAN,
		.pid_b = PID_CECILIA,
		.chapter = CHAPTER_16,
		.msg = MSG_2A8,
		.flag = EVT_FLAG(22),
	},
	{
		.pid_a = PID_NARCIAN,
		.pid_b = PID_PERCEVAL,
		.chapter = CHAPTER_16,
		.msg = MSG_2A9,
		.flag = EVT_FLAG(23),
	},
	{
		.pid_a = PID_MURDOCK,
		.pid_b = PID_ZEISS,
		.chapter = CHAPTER_21,
		.msg = MSG_2AA,
		.flag = EVT_FLAG(21),
	},
	{
		.pid_a = PID_MURDOCK,
		.pid_b = PID_MELADY,
		.chapter = CHAPTER_21,
		.msg = MSG_2AB,
		.flag = EVT_FLAG(22),
	},
	{
		.pid_a = PID_MURDOCK,
		.pid_b = PID_ROY,
		.chapter = CHAPTER_21,
		.msg = MSG_2AC,
		.flag = EVT_FLAG(23),
	},
	{
		.pid_a = PID_BRUNNYA,
		.pid_b = PID_ZEISS,
		.chapter = CHAPTER_23,
		.msg = MSG_2AD,
		.flag = EVT_FLAG(10),
	},
	{
		.pid_a = PID_BRUNNYA,
		.pid_b = PID_MELADY,
		.chapter = CHAPTER_23,
		.msg = MSG_2AE,
		.flag = EVT_FLAG(11),
	},
	{
		.pid_a = PID_UNKNOWN_69,
		.pid_b = PID_SIN,
		.chapter = CHAPTER_18_S,
		.msg = MSG_2B0,
		.flag = EVT_FLAG(12),
	},
	{
		.pid_a = PID_UNKNOWN_69,
		.pid_b = PID_SUE,
		.chapter = CHAPTER_18_S,
		.msg = MSG_2B1,
		.flag = EVT_FLAG(13),
	},
	{
		.pid_a = PID_UNKNOWN_60,
		.pid_b = PID_THEA,
		.chapter = CHAPTER_19_I,
		.msg = MSG_2B2,
		.flag = EVT_FLAG(8),
	},
	{
		.pid_a = PID_UNKNOWN_60,
		.pid_b = PID_SHANNA,
		.chapter = CHAPTER_19_I,
		.msg = MSG_2B3,
		.flag = EVT_FLAG(9),
	},
	{
		.pid_a = PID_UNKNOWN_51,
		.pid_b = PID_LILINA,
		.chapter = CHAPTER_8,
		.msg = MSG_2B4,
		.flag = EVT_FLAG(16),
	},
	{
		.pid_a = PID_UNKNOWN_51,
		.pid_b = PID_BARTHE,
		.chapter = CHAPTER_8,
		.msg = MSG_2B5,
		.flag = EVT_FLAG(17),
	},
	{
		.pid_a = PID_UNKNOWN_51,
		.pid_b = PID_BORS,
		.chapter = CHAPTER_8,
		.msg = MSG_2B6,
		.flag = EVT_FLAG(18),
	},
	{
		.pid_a = PID_UNKNOWN_51,
		.pid_b = PID_GWENDOLYN,
		.chapter = CHAPTER_8,
		.msg = MSG_2B7,
		.flag = EVT_FLAG(19),
	},
	{
		.pid_a = PID_UNKNOWN_50,
		.pid_b = PID_BORS,
		.chapter = CHAPTER_7,
		.msg = MSG_2B8,
		.flag = EVT_FLAG(15),
	},
	{
		.pid_a = PID_UNKNOWN_5E,
		.pid_b = PID_KLEIN,
		.chapter = CHAPTER_17_I,
		.msg = MSG_2B9,
		.flag = EVT_FLAG(10),
	},
	{
		.pid_a = PID_UNKNOWN_5E,
		.pid_b = PID_DOUGLAS,
		.chapter = CHAPTER_17_I,
		.msg = MSG_2BA,
		.flag = EVT_FLAG(11),
	},
	{
		.pid_a = PID_UNKNOWN_61,
		.pid_b = PID_DOUGLAS,
		.chapter = CHAPTER_20_I,
		.msg = MSG_2BB,
		.flag = EVT_FLAG(14),
	},
	{
		.pid_a = PID_UNKNOWN_5E,
		.pid_b = PID_KLEIN,
		.chapter = CHAPTER_17_S,
		.msg = MSG_2B9,
		.flag = EVT_FLAG(10),
	},
	{
		.pid_a = PID_UNKNOWN_5E,
		.pid_b = PID_DOUGLAS,
		.chapter = CHAPTER_17_S,
		.msg = MSG_2BA,
		.flag = EVT_FLAG(11),
	},
	{
		.pid_a = PID_UNKNOWN_61,
		.pid_b = PID_DOUGLAS,
		.chapter = CHAPTER_20_S,
		.msg = MSG_2BB,
		.flag = EVT_FLAG(14),
	},
	{
		.pid_a = PID_UNKNOWN_56,
		.pid_b = PID_ELEN,
		.chapter = CHAPTER_11_A,
		.msg = MSG_2BC,
		.flag = EVT_FLAG(24),
	},
	{
		.pid_a = PID_UNKNOWN_56,
		.pid_b = PID_SAUL,
		.chapter = CHAPTER_11_A,
		.msg = MSG_2BD,
		.flag = EVT_FLAG(25),
	},
	{}, {}
};

struct BattleTalkEnt CONST_DATA gTriangleAttackTalkList[] = {
	{
		.pid = PID_JUNO,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_1AF,
		.flag = EVT_FLAG(115),
		.unk_0C = 0
	},
	{
		.pid = PID_THEA,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_1B0,
		.flag = EVT_FLAG(116),
		.unk_0C = 0
	},
	{
		.pid = PID_SHANNA,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_1B1,
		.flag = EVT_FLAG(117),
		.unk_0C = 0
	},
	{
		.pid = PID_BARTHE,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_0C4,
		.flag = EVT_FLAG(120),
		.unk_0C = 0
	},
	{
		.pid = PID_BORS,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_0C5,
		.flag = EVT_FLAG(121),
		.unk_0C = 0
	},
	{
		.pid = PID_GWENDOLYN,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_0C6,
		.flag = EVT_FLAG(122),
		.unk_0C = 0
	},
	{}
};

struct BattleTalkEnt CONST_DATA gBattleDefeatTalkList[] = {
	{
		.pid = PID_CECILIA,
		.chapter = CHAPTER_13,
		.msg = MSG_000,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_233,
	},
	{
		.pid = PID_ROY,
		.chapter = CHAPTER_TUTORIAL,
		.msg = MSG_046,
		.flag = EVT_FLAG(101),
		.unk_0C = 0
	},
	{
		.pid = PID_LILINA,
		.chapter = CHAPTER_TUTORIAL,
		.msg = MSG_047,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_221,
	},
	{
		.pid = PID_WOLT,
		.chapter = CHAPTER_TUTORIAL,
		.msg = MSG_048,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_20B,
	},
	{
		.pid = PID_CLARINE,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_26C,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_202,
	},
	{
		.pid = PID_FAE,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_26D,
		.flag = EVT_FLAG(108),
		.unk_0C = MSG_203,
	},
	{
		.pid = PID_SIN,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_26E,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_204,
	},
	{
		.pid = PID_SUE,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_26F,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_205,
	},
	{
		.pid = PID_DAYAN,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_270,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_206,
	},
	{
		.pid = PID_BARTHE,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_271,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_207,
	},
	{
		.pid = PID_BORS,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_272,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_208,
	},
	{
		.pid = PID_GWENDOLYN,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_273,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_209,
	},
	{
		.pid = PID_DOUGLAS,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_274,
		.flag = EVT_FLAG(110),
		.unk_0C = MSG_20A,
	},
	{
		.pid = PID_WOLT,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_275,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_20B,
	},
	{
		.pid = PID_DOROTHY,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_276,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_20C,
	},
	{
		.pid = PID_KLEIN,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_277,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_20D,
	},
	{
		.pid = PID_SAUL,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_278,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_20E,
	},
	{
		.pid = PID_ELEN,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_279,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_20F,
	},
	{
		.pid = PID_YODER,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_27A,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_210,
	},
	{
		.pid = PID_CHAD,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_27B,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_211,
	},
	{
		.pid = PID_KAREL,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_27C,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_212,
	},
	{
		.pid = PID_FIR,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_27D,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_213,
	},
	{
		.pid = PID_RUTGER,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_27E,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_214,
	},
	{
		.pid = PID_DIECK,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_27F,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_215,
	},
	{
		.pid = PID_GARRET,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_280,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_216,
	},
	{
		.pid = PID_ALEN,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_281,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_217,
	},
	{
		.pid = PID_LANCE,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_282,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_218,
	},
	{
		.pid = PID_PERCEVAL,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_283,
		.flag = EVT_FLAG(111),
		.unk_0C = MSG_219,
	},
	{
		.pid = PID_IGRENE,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_284,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_21A,
	},
	{
		.pid = PID_MARCUS,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_285,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_21B,
	},
	{
		.pid = PID_ASTOLFO,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_286,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_21C,
	},
	{
		.pid = PID_WARD,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_287,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_21D,
	},
	{
		.pid = PID_LOT,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_288,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_21E,
	},
	{
		.pid = PID_BARTRE,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_289,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_21F,
	},
	{
		.pid = PID_LUGH,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_28A,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_220,
	},
	{
		.pid = PID_LILINA,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_28B,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_221,
	},
	{
		.pid = PID_HUGH,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_28C,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_222,
	},
	{
		.pid = PID_NIIME,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_28D,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_223,
	},
	{
		.pid = PID_RAIGH,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_28E,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_224,
	},
	{
		.pid = PID_LARUM,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_28F,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_225,
	},
	{
		.pid = PID_JUNO,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_290,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_226,
	},
	{
		.pid = PID_THEA,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_291,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_227,
	},
	{
		.pid = PID_SHANNA,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_292,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_228,
	},
	{
		.pid = PID_ZEISS,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_293,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_229,
	},
	{
		.pid = PID_ELFFIN,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_294,
		.flag = EVT_FLAG(118),
		.unk_0C = MSG_22A,
	},
	{
		.pid = PID_CATH,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_295,
		.flag = EVT_FLAG(112),
		.unk_0C = MSG_22B,
	},
	{
		.pid = PID_SOPHIA,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_296,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_22C,
	},
	{
		.pid = PID_MELADY,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_297,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_22D,
	},
	{
		.pid = PID_GONZALEZ,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_298,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_22E,
	},
	{
		.pid = PID_NOAH,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_299,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_22F,
	},
	{
		.pid = PID_TREC,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_29A,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_230,
	},
	{
		.pid = PID_ZELOT,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_29B,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_231,
	},
	{
		.pid = PID_ECHIDNA,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_29C,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_232,
	},
	{
		.pid = PID_CECILIA,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_29D,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_233,
	},
	{
		.pid = PID_GEESE,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_29E,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_234,
	},
	{
		.pid = PID_MERLINUS,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_2A0,
		.flag = EVT_FLAG(0),
		.unk_0C = 0
	},
	{
		.pid = PID_OGIER,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_29F,
		.flag = EVT_FLAG(0),
		.unk_0C = MSG_235,
	},
	{
		.pid = PID_CHAPTER1_4A,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_00F,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_CHAPTER2_4B,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_05D,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_4C,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_06D,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_4D,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_07F,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_4E,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_08B,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_4F,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_094,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_50,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_0B0,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_51,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_0BC,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_B5,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_BD6,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_52,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_0D8,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_53,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_0E9,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_56,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_101,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_58,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_112,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_B8,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_BDC,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_55,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_132,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_5A,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_141,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_5B,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_13E,
		.flag = EVT_FLAG(0),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_5C,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_13F,
		.flag = EVT_FLAG(0),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_B9,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_BE2,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_5D,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_152,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_NARCIAN,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_170,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_C6,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_BEA,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_5E,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_182,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_5F,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_192,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_60,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_19E,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_61,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_1AC,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_BA,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_BF4,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_MURDOCK,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_1BE,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_GALLE,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_2BE,
		.flag = EVT_FLAG(109),
		.unk_0C = 0
	},
	{
		.pid = PID_ZEPHIEL,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_1CC,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_BRUNNYA,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_1F4,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_JAHN,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_1FE,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_IDUNN,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_238,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_IDUNN_DRAGON,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_238,
		.flag = EVT_FLAG(114),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_68,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_967,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_C8,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_977,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_69,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_991,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_6A,
		.chapter = TALK_CHAPTER_ANY,
		.msg = MSG_99F,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_KLEIN_SQUAD,
		.chapter = CHAPTER_10_B,
		.msg = MSG_000,
		.flag = EVT_FLAG(17),
		.unk_0C = 0
	},
	{
		.pid = PID_THEA_SQUAD,
		.chapter = CHAPTER_10_B,
		.msg = MSG_000,
		.flag = EVT_FLAG(18),
		.unk_0C = 0
	},
	{
		.pid = PID_KLEIN_SQUAD,
		.chapter = CHAPTER_11_A,
		.msg = MSG_000,
		.flag = EVT_FLAG(22),
		.unk_0C = 0
	},
	{
		.pid = PID_THEA_SQUAD,
		.chapter = CHAPTER_11_A,
		.msg = MSG_000,
		.flag = EVT_FLAG(23),
		.unk_0C = 0
	},
	{
		.pid = PID_CITIZEN_A4,
		.chapter = CHAPTER_11_B,
		.msg = MSG_000,
		.flag = EVT_FLAG(14),
		.unk_0C = 0
	},
	{
		.pid = PID_CITIZEN_CD,
		.chapter = CHAPTER_11_B,
		.msg = MSG_000,
		.flag = EVT_FLAG(14),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_D5,
		.chapter = CHAPTER_13,
		.msg = MSG_000,
		.flag = EVT_FLAG(14),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_D6,
		.chapter = CHAPTER_13,
		.msg = MSG_000,
		.flag = EVT_FLAG(14),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_D7,
		.chapter = CHAPTER_13,
		.msg = MSG_000,
		.flag = EVT_FLAG(14),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_D3,
		.chapter = CHAPTER_15,
		.msg = MSG_000,
		.flag = EVT_FLAG(11),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_9D,
		.chapter = CHAPTER_20_I,
		.msg = MSG_000,
		.flag = EVT_FLAG(13),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_CE,
		.chapter = CHAPTER_20_I,
		.msg = MSG_000,
		.flag = EVT_FLAG(13),
		.unk_0C = 0
	},
	{
		.pid = PID_UNKNOWN_C4,
		.chapter = CHAPTER_21X,
		.msg = MSG_C05,
		.flag = EVT_FLAG(2),
		.unk_0C = 0
	},
	{
		.pid = PID_BORS_TUTORIAL,
		.chapter = CHAPTER_TUTORIAL,
		.msg = MSG_04C,
		.flag = EVT_FLAG(0),
		.unk_0C = 0
	},
	{}
};

struct HardModeBonusLevelsOverrideEnt CONST_DATA gHardModeBonusLevelsOverrideList[] = {
	{
		.pid = PID_RUTGER,
		.bonus_levels = 0,
	},
	{
		.pid = PID_CATH,
		.bonus_levels = 0,
	},
	{
		.pid = PID_FIR,
		.bonus_levels = 0,
	},
	{
		.pid = PID_SIN,
		.bonus_levels = 0,
	},
	{
		.pid = PID_GONZALEZ,
		.bonus_levels = 0,
	},
	{
		.pid = PID_KLEIN,
		.bonus_levels = 0,
	},
	{
		.pid = PID_THEA,
		.bonus_levels = 0,
	},
	{
		.pid = PID_RAIGH,
		.bonus_levels = 0,
	},
	{
		.pid = PID_MELADY,
		.bonus_levels = 0,
	},
	{
		.pid = PID_CECILIA,
		.bonus_levels = 0,
	},
	{
		.pid = PID_PERCEVAL,
		.bonus_levels = 0,
	},
	{
		.pid = PID_GARRET,
		.bonus_levels = 0,
	},
	{
		.pid = PID_HUGH,
		.bonus_levels = 0,
	},
	{
		.pid = PID_ZEISS,
		.bonus_levels = 0,
	},
	{
		.pid = PID_DOUGLAS,
		.bonus_levels = 0,
	},
	{}
};

struct SupportTalkEnt CONST_DATA gSupportTalkList[] = {
	{
		.pid_a = PID_ROY,
		.pid_b = PID_LILINA,
		.msg_talk_c = MSG_TALK_SUPPORT_00,
		.msg_talk_b = MSG_TALK_SUPPORT_01,
		.msg_talk_a = MSG_TALK_SUPPORT_02,
	},
	{
		.pid_a = PID_ROY,
		.pid_b = PID_MARCUS,
		.msg_talk_c = MSG_TALK_SUPPORT_03,
		.msg_talk_b = MSG_TALK_SUPPORT_04,
		.msg_talk_a = MSG_TALK_SUPPORT_05,
	},
	{
		.pid_a = PID_ROY,
		.pid_b = PID_WOLT,
		.msg_talk_c = MSG_TALK_SUPPORT_06,
		.msg_talk_b = MSG_TALK_SUPPORT_07,
		.msg_talk_a = MSG_TALK_SUPPORT_08,
	},
	{
		.pid_a = PID_ROY,
		.pid_b = PID_CECILIA,
		.msg_talk_c = MSG_TALK_SUPPORT_09,
		.msg_talk_b = MSG_TALK_SUPPORT_0A,
		.msg_talk_a = MSG_TALK_SUPPORT_0B,
	},
	{
		.pid_a = PID_ROY,
		.pid_b = PID_SOPHIA,
		.msg_talk_c = MSG_TALK_SUPPORT_0C,
		.msg_talk_b = MSG_TALK_SUPPORT_0D,
		.msg_talk_a = MSG_TALK_SUPPORT_0E,
	},
	{
		.pid_a = PID_ROY,
		.pid_b = PID_SUE,
		.msg_talk_c = MSG_TALK_SUPPORT_0F,
		.msg_talk_b = MSG_TALK_SUPPORT_10,
		.msg_talk_a = MSG_TALK_SUPPORT_11,
	},
	{
		.pid_a = PID_ROY,
		.pid_b = PID_SHANNA,
		.msg_talk_c = MSG_TALK_SUPPORT_12,
		.msg_talk_b = MSG_TALK_SUPPORT_13,
		.msg_talk_a = MSG_TALK_SUPPORT_14,
	},
	{
		.pid_a = PID_ROY,
		.pid_b = PID_LARUM,
		.msg_talk_c = MSG_TALK_SUPPORT_15,
		.msg_talk_b = MSG_TALK_SUPPORT_16,
		.msg_talk_a = MSG_TALK_SUPPORT_17,
	},
	{
		.pid_a = PID_ROY,
		.pid_b = PID_ALEN,
		.msg_talk_c = MSG_TALK_SUPPORT_18,
		.msg_talk_b = MSG_TALK_SUPPORT_19,
		.msg_talk_a = MSG_TALK_SUPPORT_1A,
	},
	{
		.pid_a = PID_ROY,
		.pid_b = PID_LANCE,
		.msg_talk_c = MSG_TALK_SUPPORT_1B,
		.msg_talk_b = MSG_TALK_SUPPORT_1C,
		.msg_talk_a = MSG_TALK_SUPPORT_1D,
	},
	{
		.pid_a = PID_CLARINE,
		.pid_b = PID_KLEIN,
		.msg_talk_c = MSG_TALK_SUPPORT_1E,
		.msg_talk_b = MSG_TALK_SUPPORT_1F,
		.msg_talk_a = MSG_TALK_SUPPORT_20,
	},
	{
		.pid_a = PID_CLARINE,
		.pid_b = PID_RUTGER,
		.msg_talk_c = MSG_TALK_SUPPORT_21,
		.msg_talk_b = MSG_TALK_SUPPORT_22,
		.msg_talk_a = MSG_TALK_SUPPORT_23,
	},
	{
		.pid_a = PID_CLARINE,
		.pid_b = PID_DIECK,
		.msg_talk_c = MSG_TALK_SUPPORT_24,
		.msg_talk_b = MSG_TALK_SUPPORT_25,
		.msg_talk_a = MSG_TALK_SUPPORT_26,
	},
	{
		.pid_a = PID_CLARINE,
		.pid_b = PID_LANCE,
		.msg_talk_c = MSG_TALK_SUPPORT_27,
		.msg_talk_b = MSG_TALK_SUPPORT_28,
		.msg_talk_a = MSG_TALK_SUPPORT_29,
	},
	{
		.pid_a = PID_CLARINE,
		.pid_b = PID_DOROTHY,
		.msg_talk_c = MSG_TALK_SUPPORT_2A,
		.msg_talk_b = MSG_TALK_SUPPORT_2B,
		.msg_talk_a = MSG_TALK_SUPPORT_2C,
	},
	{
		.pid_a = PID_FAE,
		.pid_b = PID_SOPHIA,
		.msg_talk_c = MSG_TALK_SUPPORT_2D,
		.msg_talk_b = MSG_TALK_SUPPORT_2E,
		.msg_talk_a = MSG_TALK_SUPPORT_2F,
	},
	{
		.pid_a = PID_FAE,
		.pid_b = PID_IGRENE,
		.msg_talk_c = MSG_TALK_SUPPORT_30,
		.msg_talk_b = MSG_TALK_SUPPORT_31,
		.msg_talk_a = MSG_TALK_SUPPORT_32,
	},
	{
		.pid_a = PID_FAE,
		.pid_b = PID_SUE,
		.msg_talk_c = MSG_TALK_SUPPORT_33,
		.msg_talk_b = MSG_TALK_SUPPORT_34,
		.msg_talk_a = MSG_TALK_SUPPORT_35,
	},
	{
		.pid_a = PID_FAE,
		.pid_b = PID_NIIME,
		.msg_talk_c = MSG_TALK_SUPPORT_36,
		.msg_talk_b = MSG_TALK_SUPPORT_37,
		.msg_talk_a = MSG_TALK_SUPPORT_38,
	},
	{
		.pid_a = PID_FAE,
		.pid_b = PID_ELFFIN,
		.msg_talk_c = MSG_TALK_SUPPORT_39,
		.msg_talk_b = MSG_TALK_SUPPORT_3A,
		.msg_talk_a = MSG_TALK_SUPPORT_3B,
	},
	{
		.pid_a = PID_SIN,
		.pid_b = PID_DAYAN,
		.msg_talk_c = MSG_TALK_SUPPORT_3C,
		.msg_talk_b = MSG_TALK_SUPPORT_3D,
		.msg_talk_a = MSG_TALK_SUPPORT_3E,
	},
	{
		.pid_a = PID_SIN,
		.pid_b = PID_SUE,
		.msg_talk_c = MSG_TALK_SUPPORT_3F,
		.msg_talk_b = MSG_TALK_SUPPORT_40,
		.msg_talk_a = MSG_TALK_SUPPORT_41,
	},
	{
		.pid_a = PID_SIN,
		.pid_b = PID_FIR,
		.msg_talk_c = MSG_TALK_SUPPORT_42,
		.msg_talk_b = MSG_TALK_SUPPORT_43,
		.msg_talk_a = MSG_TALK_SUPPORT_44,
	},
	{
		.pid_a = PID_SIN,
		.pid_b = PID_DOROTHY,
		.msg_talk_c = MSG_TALK_SUPPORT_45,
		.msg_talk_b = MSG_TALK_SUPPORT_46,
		.msg_talk_a = MSG_TALK_SUPPORT_47,
	},
	{
		.pid_a = PID_SIN,
		.pid_b = PID_ZEISS,
		.msg_talk_c = MSG_TALK_SUPPORT_48,
		.msg_talk_b = MSG_TALK_SUPPORT_49,
		.msg_talk_a = MSG_TALK_SUPPORT_4A,
	},
	{
		.pid_a = PID_SUE,
		.pid_b = PID_DAYAN,
		.msg_talk_c = MSG_TALK_SUPPORT_4B,
		.msg_talk_b = MSG_TALK_SUPPORT_4C,
		.msg_talk_a = MSG_TALK_SUPPORT_4D,
	},
	{
		.pid_a = PID_SUE,
		.pid_b = PID_WOLT,
		.msg_talk_c = MSG_TALK_SUPPORT_4E,
		.msg_talk_b = MSG_TALK_SUPPORT_4F,
		.msg_talk_a = MSG_TALK_SUPPORT_50,
	},
	{
		.pid_a = PID_DAYAN,
		.pid_b = PID_YODER,
		.msg_talk_c = MSG_TALK_SUPPORT_51,
		.msg_talk_b = MSG_TALK_SUPPORT_52,
		.msg_talk_a = MSG_TALK_SUPPORT_53,
	},
	{
		.pid_a = PID_DAYAN,
		.pid_b = PID_GONZALEZ,
		.msg_talk_c = MSG_TALK_SUPPORT_54,
		.msg_talk_b = MSG_TALK_SUPPORT_55,
		.msg_talk_a = MSG_TALK_SUPPORT_56,
	},
	{
		.pid_a = PID_DAYAN,
		.pid_b = PID_RUTGER,
		.msg_talk_c = MSG_TALK_SUPPORT_57,
		.msg_talk_b = MSG_TALK_SUPPORT_58,
		.msg_talk_a = MSG_TALK_SUPPORT_59,
	},
	{
		.pid_a = PID_BARTHE,
		.pid_b = PID_LILINA,
		.msg_talk_c = MSG_TALK_SUPPORT_5A,
		.msg_talk_b = MSG_TALK_SUPPORT_5B,
		.msg_talk_a = MSG_TALK_SUPPORT_5C,
	},
	{
		.pid_a = PID_BARTHE,
		.pid_b = PID_OGIER,
		.msg_talk_c = MSG_TALK_SUPPORT_5D,
		.msg_talk_b = MSG_TALK_SUPPORT_5E,
		.msg_talk_a = MSG_TALK_SUPPORT_5F,
	},
	{
		.pid_a = PID_BARTHE,
		.pid_b = PID_BORS,
		.msg_talk_c = MSG_TALK_SUPPORT_60,
		.msg_talk_b = MSG_TALK_SUPPORT_61,
		.msg_talk_a = MSG_TALK_SUPPORT_62,
	},
	{
		.pid_a = PID_BARTHE,
		.pid_b = PID_GWENDOLYN,
		.msg_talk_c = MSG_TALK_SUPPORT_63,
		.msg_talk_b = MSG_TALK_SUPPORT_64,
		.msg_talk_a = MSG_TALK_SUPPORT_65,
	},
	{
		.pid_a = PID_BARTHE,
		.pid_b = PID_ASTOLFO,
		.msg_talk_c = MSG_TALK_SUPPORT_66,
		.msg_talk_b = MSG_TALK_SUPPORT_67,
		.msg_talk_a = MSG_TALK_SUPPORT_68,
	},
	{
		.pid_a = PID_BORS,
		.pid_b = PID_LILINA,
		.msg_talk_c = MSG_TALK_SUPPORT_69,
		.msg_talk_b = MSG_TALK_SUPPORT_6A,
		.msg_talk_a = MSG_TALK_SUPPORT_6B,
	},
	{
		.pid_a = PID_BORS,
		.pid_b = PID_GWENDOLYN,
		.msg_talk_c = MSG_TALK_SUPPORT_6C,
		.msg_talk_b = MSG_TALK_SUPPORT_6D,
		.msg_talk_a = MSG_TALK_SUPPORT_6E,
	},
	{
		.pid_a = PID_BORS,
		.pid_b = PID_ASTOLFO,
		.msg_talk_c = MSG_TALK_SUPPORT_6F,
		.msg_talk_b = MSG_TALK_SUPPORT_70,
		.msg_talk_a = MSG_TALK_SUPPORT_71,
	},
	{
		.pid_a = PID_BORS,
		.pid_b = PID_OGIER,
		.msg_talk_c = MSG_TALK_SUPPORT_72,
		.msg_talk_b = MSG_TALK_SUPPORT_73,
		.msg_talk_a = MSG_TALK_SUPPORT_74,
	},
	{
		.pid_a = PID_GWENDOLYN,
		.pid_b = PID_LILINA,
		.msg_talk_c = MSG_TALK_SUPPORT_75,
		.msg_talk_b = MSG_TALK_SUPPORT_76,
		.msg_talk_a = MSG_TALK_SUPPORT_77,
	},
	{
		.pid_a = PID_GWENDOLYN,
		.pid_b = PID_OGIER,
		.msg_talk_c = MSG_TALK_SUPPORT_78,
		.msg_talk_b = MSG_TALK_SUPPORT_79,
		.msg_talk_a = MSG_TALK_SUPPORT_7A,
	},
	{
		.pid_a = PID_GWENDOLYN,
		.pid_b = PID_ASTOLFO,
		.msg_talk_c = MSG_TALK_SUPPORT_7B,
		.msg_talk_b = MSG_TALK_SUPPORT_7C,
		.msg_talk_a = MSG_TALK_SUPPORT_7D,
	},
	{
		.pid_a = PID_DOUGLAS,
		.pid_b = PID_ELFFIN,
		.msg_talk_c = MSG_TALK_SUPPORT_7E,
		.msg_talk_b = MSG_TALK_SUPPORT_7F,
		.msg_talk_a = MSG_TALK_SUPPORT_80,
	},
	{
		.pid_a = PID_DOUGLAS,
		.pid_b = PID_GEESE,
		.msg_talk_c = MSG_TALK_SUPPORT_81,
		.msg_talk_b = MSG_TALK_SUPPORT_82,
		.msg_talk_a = MSG_TALK_SUPPORT_83,
	},
	{
		.pid_a = PID_DOUGLAS,
		.pid_b = PID_IGRENE,
		.msg_talk_c = MSG_TALK_SUPPORT_84,
		.msg_talk_b = MSG_TALK_SUPPORT_85,
		.msg_talk_a = MSG_TALK_SUPPORT_86,
	},
	{
		.pid_a = PID_DOUGLAS,
		.pid_b = PID_PERCEVAL,
		.msg_talk_c = MSG_TALK_SUPPORT_87,
		.msg_talk_b = MSG_TALK_SUPPORT_88,
		.msg_talk_a = MSG_TALK_SUPPORT_89,
	},
	{
		.pid_a = PID_DOUGLAS,
		.pid_b = PID_CECILIA,
		.msg_talk_c = MSG_TALK_SUPPORT_8A,
		.msg_talk_b = MSG_TALK_SUPPORT_8B,
		.msg_talk_a = MSG_TALK_SUPPORT_8C,
	},
	{
		.pid_a = PID_DOUGLAS,
		.pid_b = PID_LARUM,
		.msg_talk_c = MSG_TALK_SUPPORT_8D,
		.msg_talk_b = MSG_TALK_SUPPORT_8E,
		.msg_talk_a = MSG_TALK_SUPPORT_8F,
	},
	{
		.pid_a = PID_WOLT,
		.pid_b = PID_MARCUS,
		.msg_talk_c = MSG_TALK_SUPPORT_90,
		.msg_talk_b = MSG_TALK_SUPPORT_91,
		.msg_talk_a = MSG_TALK_SUPPORT_92,
	},
	{
		.pid_a = PID_WOLT,
		.pid_b = PID_ALEN,
		.msg_talk_c = MSG_TALK_SUPPORT_93,
		.msg_talk_b = MSG_TALK_SUPPORT_94,
		.msg_talk_a = MSG_TALK_SUPPORT_95,
	},
	{
		.pid_a = PID_WOLT,
		.pid_b = PID_LANCE,
		.msg_talk_c = MSG_TALK_SUPPORT_96,
		.msg_talk_b = MSG_TALK_SUPPORT_97,
		.msg_talk_a = MSG_TALK_SUPPORT_98,
	},
	{
		.pid_a = PID_DOROTHY,
		.pid_b = PID_SAUL,
		.msg_talk_c = MSG_TALK_SUPPORT_99,
		.msg_talk_b = MSG_TALK_SUPPORT_9A,
		.msg_talk_a = MSG_TALK_SUPPORT_9B,
	},
	{
		.pid_a = PID_DOROTHY,
		.pid_b = PID_PERCEVAL,
		.msg_talk_c = MSG_TALK_SUPPORT_9C,
		.msg_talk_b = MSG_TALK_SUPPORT_9D,
		.msg_talk_a = MSG_TALK_SUPPORT_9E,
	},
	{
		.pid_a = PID_DOROTHY,
		.pid_b = PID_YODER,
		.msg_talk_c = MSG_TALK_SUPPORT_9F,
		.msg_talk_b = MSG_TALK_SUPPORT_A0,
		.msg_talk_a = MSG_TALK_SUPPORT_A1,
	},
	{
		.pid_a = PID_KLEIN,
		.pid_b = PID_PERCEVAL,
		.msg_talk_c = MSG_TALK_SUPPORT_A2,
		.msg_talk_b = MSG_TALK_SUPPORT_A3,
		.msg_talk_a = MSG_TALK_SUPPORT_A4,
	},
	{
		.pid_a = PID_KLEIN,
		.pid_b = PID_DIECK,
		.msg_talk_c = MSG_TALK_SUPPORT_A5,
		.msg_talk_b = MSG_TALK_SUPPORT_A6,
		.msg_talk_a = MSG_TALK_SUPPORT_A7,
	},
	{
		.pid_a = PID_KLEIN,
		.pid_b = PID_ELFFIN,
		.msg_talk_c = MSG_TALK_SUPPORT_A8,
		.msg_talk_b = MSG_TALK_SUPPORT_A9,
		.msg_talk_a = MSG_TALK_SUPPORT_AA,
	},
	{
		.pid_a = PID_KLEIN,
		.pid_b = PID_THEA,
		.msg_talk_c = MSG_TALK_SUPPORT_AB,
		.msg_talk_b = MSG_TALK_SUPPORT_AC,
		.msg_talk_a = MSG_TALK_SUPPORT_AD,
	},
	{
		.pid_a = PID_SAUL,
		.pid_b = PID_YODER,
		.msg_talk_c = MSG_TALK_SUPPORT_AE,
		.msg_talk_b = MSG_TALK_SUPPORT_AF,
		.msg_talk_a = MSG_TALK_SUPPORT_B0,
	},
	{
		.pid_a = PID_SAUL,
		.pid_b = PID_CECILIA,
		.msg_talk_c = MSG_TALK_SUPPORT_B1,
		.msg_talk_b = MSG_TALK_SUPPORT_B2,
		.msg_talk_a = MSG_TALK_SUPPORT_B3,
	},
	{
		.pid_a = PID_SAUL,
		.pid_b = PID_IGRENE,
		.msg_talk_c = MSG_TALK_SUPPORT_B4,
		.msg_talk_b = MSG_TALK_SUPPORT_B5,
		.msg_talk_a = MSG_TALK_SUPPORT_B6,
	},
	{
		.pid_a = PID_SAUL,
		.pid_b = PID_ELEN,
		.msg_talk_c = MSG_TALK_SUPPORT_B7,
		.msg_talk_b = MSG_TALK_SUPPORT_B8,
		.msg_talk_a = MSG_TALK_SUPPORT_B9,
	},
	{
		.pid_a = PID_ELEN,
		.pid_b = PID_MELADY,
		.msg_talk_c = MSG_TALK_SUPPORT_BA,
		.msg_talk_b = MSG_TALK_SUPPORT_BB,
		.msg_talk_a = MSG_TALK_SUPPORT_BC,
	},
	{
		.pid_a = PID_ELEN,
		.pid_b = PID_ZEISS,
		.msg_talk_c = MSG_TALK_SUPPORT_BD,
		.msg_talk_b = MSG_TALK_SUPPORT_BE,
		.msg_talk_a = MSG_TALK_SUPPORT_BF,
	},
	{
		.pid_a = PID_ELEN,
		.pid_b = PID_LUGH,
		.msg_talk_c = MSG_TALK_SUPPORT_C0,
		.msg_talk_b = MSG_TALK_SUPPORT_C1,
		.msg_talk_a = MSG_TALK_SUPPORT_C2,
	},
	{
		.pid_a = PID_ELEN,
		.pid_b = PID_CHAD,
		.msg_talk_c = MSG_TALK_SUPPORT_C3,
		.msg_talk_b = MSG_TALK_SUPPORT_C4,
		.msg_talk_a = MSG_TALK_SUPPORT_C5,
	},
	{
		.pid_a = PID_YODER,
		.pid_b = PID_NIIME,
		.msg_talk_c = MSG_TALK_SUPPORT_C6,
		.msg_talk_b = MSG_TALK_SUPPORT_C7,
		.msg_talk_a = MSG_TALK_SUPPORT_C8,
	},
	{
		.pid_a = PID_YODER,
		.pid_b = PID_MELADY,
		.msg_talk_c = MSG_TALK_SUPPORT_C9,
		.msg_talk_b = MSG_TALK_SUPPORT_CA,
		.msg_talk_a = MSG_TALK_SUPPORT_CB,
	},
	{
		.pid_a = PID_CHAD,
		.pid_b = PID_LUGH,
		.msg_talk_c = MSG_TALK_SUPPORT_CC,
		.msg_talk_b = MSG_TALK_SUPPORT_CD,
		.msg_talk_a = MSG_TALK_SUPPORT_CE,
	},
	{
		.pid_a = PID_CHAD,
		.pid_b = PID_RAIGH,
		.msg_talk_c = MSG_TALK_SUPPORT_CF,
		.msg_talk_b = MSG_TALK_SUPPORT_D0,
		.msg_talk_a = MSG_TALK_SUPPORT_D1,
	},
	{
		.pid_a = PID_CHAD,
		.pid_b = PID_CATH,
		.msg_talk_c = MSG_TALK_SUPPORT_D2,
		.msg_talk_b = MSG_TALK_SUPPORT_D3,
		.msg_talk_a = MSG_TALK_SUPPORT_D4,
	},
	{
		.pid_a = PID_CHAD,
		.pid_b = PID_HUGH,
		.msg_talk_c = MSG_TALK_SUPPORT_D5,
		.msg_talk_b = MSG_TALK_SUPPORT_D6,
		.msg_talk_a = MSG_TALK_SUPPORT_D7,
	},
	{
		.pid_a = PID_KAREL,
		.pid_b = PID_FIR,
		.msg_talk_c = MSG_TALK_SUPPORT_D8,
		.msg_talk_b = MSG_TALK_SUPPORT_D9,
		.msg_talk_a = MSG_TALK_SUPPORT_DA,
	},
	{
		.pid_a = PID_KAREL,
		.pid_b = PID_BARTRE,
		.msg_talk_c = MSG_TALK_SUPPORT_DB,
		.msg_talk_b = MSG_TALK_SUPPORT_DC,
		.msg_talk_a = MSG_TALK_SUPPORT_DD,
	},
	{
		.pid_a = PID_KAREL,
		.pid_b = PID_RUTGER,
		.msg_talk_c = MSG_TALK_SUPPORT_DE,
		.msg_talk_b = MSG_TALK_SUPPORT_DF,
		.msg_talk_a = MSG_TALK_SUPPORT_E0,
	},
	{
		.pid_a = PID_KAREL,
		.pid_b = PID_ZEISS,
		.msg_talk_c = MSG_TALK_SUPPORT_E1,
		.msg_talk_b = MSG_TALK_SUPPORT_E2,
		.msg_talk_a = MSG_TALK_SUPPORT_E3,
	},
	{
		.pid_a = PID_KAREL,
		.pid_b = PID_NOAH,
		.msg_talk_c = MSG_TALK_SUPPORT_E4,
		.msg_talk_b = MSG_TALK_SUPPORT_E5,
		.msg_talk_a = MSG_TALK_SUPPORT_E6,
	},
	{
		.pid_a = PID_FIR,
		.pid_b = PID_BARTRE,
		.msg_talk_c = MSG_TALK_SUPPORT_E7,
		.msg_talk_b = MSG_TALK_SUPPORT_E8,
		.msg_talk_a = MSG_TALK_SUPPORT_E9,
	},
	{
		.pid_a = PID_FIR,
		.pid_b = PID_NOAH,
		.msg_talk_c = MSG_TALK_SUPPORT_EA,
		.msg_talk_b = MSG_TALK_SUPPORT_EB,
		.msg_talk_a = MSG_TALK_SUPPORT_EC,
	},
	{
		.pid_a = PID_FIR,
		.pid_b = PID_RUTGER,
		.msg_talk_c = MSG_TALK_SUPPORT_ED,
		.msg_talk_b = MSG_TALK_SUPPORT_EE,
		.msg_talk_a = MSG_TALK_SUPPORT_EF,
	},
	{
		.pid_a = PID_RUTGER,
		.pid_b = PID_DIECK,
		.msg_talk_c = MSG_TALK_SUPPORT_F0,
		.msg_talk_b = MSG_TALK_SUPPORT_F1,
		.msg_talk_a = MSG_TALK_SUPPORT_F2,
	},
	{
		.pid_a = PID_DIECK,
		.pid_b = PID_WARD,
		.msg_talk_c = MSG_TALK_SUPPORT_F3,
		.msg_talk_b = MSG_TALK_SUPPORT_F4,
		.msg_talk_a = MSG_TALK_SUPPORT_F5,
	},
	{
		.pid_a = PID_DIECK,
		.pid_b = PID_LOT,
		.msg_talk_c = MSG_TALK_SUPPORT_F6,
		.msg_talk_b = MSG_TALK_SUPPORT_F7,
		.msg_talk_a = MSG_TALK_SUPPORT_F8,
	},
	{
		.pid_a = PID_DIECK,
		.pid_b = PID_SHANNA,
		.msg_talk_c = MSG_TALK_SUPPORT_F9,
		.msg_talk_b = MSG_TALK_SUPPORT_FA,
		.msg_talk_a = MSG_TALK_SUPPORT_FB,
	},
	{
		.pid_a = PID_OGIER,
		.pid_b = PID_LILINA,
		.msg_talk_c = MSG_TALK_SUPPORT_FC,
		.msg_talk_b = MSG_TALK_SUPPORT_FD,
		.msg_talk_a = MSG_TALK_SUPPORT_FE,
	},
	{
		.pid_a = PID_OGIER,
		.pid_b = PID_LARUM,
		.msg_talk_c = MSG_TALK_SUPPORT_FF,
		.msg_talk_b = MSG_TALK_SUPPORT_100,
		.msg_talk_a = MSG_TALK_SUPPORT_101,
	},
	{
		.pid_a = PID_GARRET,
		.pid_b = PID_LILINA,
		.msg_talk_c = MSG_TALK_SUPPORT_102,
		.msg_talk_b = MSG_TALK_SUPPORT_103,
		.msg_talk_a = MSG_TALK_SUPPORT_104,
	},
	{
		.pid_a = PID_GARRET,
		.pid_b = PID_GEESE,
		.msg_talk_c = MSG_TALK_SUPPORT_105,
		.msg_talk_b = MSG_TALK_SUPPORT_106,
		.msg_talk_a = MSG_TALK_SUPPORT_107,
	},
	{
		.pid_a = PID_GARRET,
		.pid_b = PID_LARUM,
		.msg_talk_c = MSG_TALK_SUPPORT_108,
		.msg_talk_b = MSG_TALK_SUPPORT_109,
		.msg_talk_a = MSG_TALK_SUPPORT_10A,
	},
	{
		.pid_a = PID_GARRET,
		.pid_b = PID_CATH,
		.msg_talk_c = MSG_TALK_SUPPORT_10B,
		.msg_talk_b = MSG_TALK_SUPPORT_10C,
		.msg_talk_a = MSG_TALK_SUPPORT_10D,
	},
	{
		.pid_a = PID_GARRET,
		.pid_b = PID_GONZALEZ,
		.msg_talk_c = MSG_TALK_SUPPORT_10E,
		.msg_talk_b = MSG_TALK_SUPPORT_10F,
		.msg_talk_a = MSG_TALK_SUPPORT_110,
	},
	{
		.pid_a = PID_ALEN,
		.pid_b = PID_THEA,
		.msg_talk_c = MSG_TALK_SUPPORT_111,
		.msg_talk_b = MSG_TALK_SUPPORT_112,
		.msg_talk_a = MSG_TALK_SUPPORT_113,
	},
	{
		.pid_a = PID_ALEN,
		.pid_b = PID_MARCUS,
		.msg_talk_c = MSG_TALK_SUPPORT_114,
		.msg_talk_b = MSG_TALK_SUPPORT_115,
		.msg_talk_a = MSG_TALK_SUPPORT_116,
	},
	{
		.pid_a = PID_ALEN,
		.pid_b = PID_LANCE,
		.msg_talk_c = MSG_TALK_SUPPORT_117,
		.msg_talk_b = MSG_TALK_SUPPORT_118,
		.msg_talk_a = MSG_TALK_SUPPORT_119,
	},
	{
		.pid_a = PID_ALEN,
		.pid_b = PID_WARD,
		.msg_talk_c = MSG_TALK_SUPPORT_11A,
		.msg_talk_b = MSG_TALK_SUPPORT_11B,
		.msg_talk_a = MSG_TALK_SUPPORT_11C,
	},
	{
		.pid_a = PID_LANCE,
		.pid_b = PID_MARCUS,
		.msg_talk_c = MSG_TALK_SUPPORT_11D,
		.msg_talk_b = MSG_TALK_SUPPORT_11E,
		.msg_talk_a = MSG_TALK_SUPPORT_11F,
	},
	{
		.pid_a = PID_LANCE,
		.pid_b = PID_LOT,
		.msg_talk_c = MSG_TALK_SUPPORT_120,
		.msg_talk_b = MSG_TALK_SUPPORT_121,
		.msg_talk_a = MSG_TALK_SUPPORT_122,
	},
	{
		.pid_a = PID_PERCEVAL,
		.pid_b = PID_CECILIA,
		.msg_talk_c = MSG_TALK_SUPPORT_123,
		.msg_talk_b = MSG_TALK_SUPPORT_124,
		.msg_talk_a = MSG_TALK_SUPPORT_125,
	},
	{
		.pid_a = PID_PERCEVAL,
		.pid_b = PID_ELFFIN,
		.msg_talk_c = MSG_TALK_SUPPORT_126,
		.msg_talk_b = MSG_TALK_SUPPORT_127,
		.msg_talk_a = MSG_TALK_SUPPORT_128,
	},
	{
		.pid_a = PID_PERCEVAL,
		.pid_b = PID_LARUM,
		.msg_talk_c = MSG_TALK_SUPPORT_129,
		.msg_talk_b = MSG_TALK_SUPPORT_12A,
		.msg_talk_a = MSG_TALK_SUPPORT_12B,
	},
	{
		.pid_a = PID_IGRENE,
		.pid_b = PID_SOPHIA,
		.msg_talk_c = MSG_TALK_SUPPORT_12C,
		.msg_talk_b = MSG_TALK_SUPPORT_12D,
		.msg_talk_a = MSG_TALK_SUPPORT_12E,
	},
	{
		.pid_a = PID_IGRENE,
		.pid_b = PID_ASTOLFO,
		.msg_talk_c = MSG_TALK_SUPPORT_12F,
		.msg_talk_b = MSG_TALK_SUPPORT_130,
		.msg_talk_a = MSG_TALK_SUPPORT_131,
	},
	{
		.pid_a = PID_MARCUS,
		.pid_b = PID_LILINA,
		.msg_talk_c = MSG_TALK_SUPPORT_132,
		.msg_talk_b = MSG_TALK_SUPPORT_133,
		.msg_talk_a = MSG_TALK_SUPPORT_134,
	},
	{
		.pid_a = PID_ASTOLFO,
		.pid_b = PID_LILINA,
		.msg_talk_c = MSG_TALK_SUPPORT_135,
		.msg_talk_b = MSG_TALK_SUPPORT_136,
		.msg_talk_a = MSG_TALK_SUPPORT_137,
	},
	{
		.pid_a = PID_WARD,
		.pid_b = PID_SHANNA,
		.msg_talk_c = MSG_TALK_SUPPORT_138,
		.msg_talk_b = MSG_TALK_SUPPORT_139,
		.msg_talk_a = MSG_TALK_SUPPORT_13A,
	},
	{
		.pid_a = PID_WARD,
		.pid_b = PID_LOT,
		.msg_talk_c = MSG_TALK_SUPPORT_13B,
		.msg_talk_b = MSG_TALK_SUPPORT_13C,
		.msg_talk_a = MSG_TALK_SUPPORT_13D,
	},
	{
		.pid_a = PID_WARD,
		.pid_b = PID_ECHIDNA,
		.msg_talk_c = MSG_TALK_SUPPORT_13E,
		.msg_talk_b = MSG_TALK_SUPPORT_13F,
		.msg_talk_a = MSG_TALK_SUPPORT_140,
	},
	{
		.pid_a = PID_LOT,
		.pid_b = PID_SHANNA,
		.msg_talk_c = MSG_TALK_SUPPORT_141,
		.msg_talk_b = MSG_TALK_SUPPORT_142,
		.msg_talk_a = MSG_TALK_SUPPORT_143,
	},
	{
		.pid_a = PID_LOT,
		.pid_b = PID_ECHIDNA,
		.msg_talk_c = MSG_TALK_SUPPORT_144,
		.msg_talk_b = MSG_TALK_SUPPORT_145,
		.msg_talk_a = MSG_TALK_SUPPORT_146,
	},
	{
		.pid_a = PID_BARTRE,
		.pid_b = PID_GONZALEZ,
		.msg_talk_c = MSG_TALK_SUPPORT_147,
		.msg_talk_b = MSG_TALK_SUPPORT_148,
		.msg_talk_a = MSG_TALK_SUPPORT_149,
	},
	{
		.pid_a = PID_BARTRE,
		.pid_b = PID_ZEISS,
		.msg_talk_c = MSG_TALK_SUPPORT_14A,
		.msg_talk_b = MSG_TALK_SUPPORT_14B,
		.msg_talk_a = MSG_TALK_SUPPORT_14C,
	},
	{
		.pid_a = PID_BARTRE,
		.pid_b = PID_CATH,
		.msg_talk_c = MSG_TALK_SUPPORT_14D,
		.msg_talk_b = MSG_TALK_SUPPORT_14E,
		.msg_talk_a = MSG_TALK_SUPPORT_14F,
	},
	{
		.pid_a = PID_LUGH,
		.pid_b = PID_RAIGH,
		.msg_talk_c = MSG_TALK_SUPPORT_150,
		.msg_talk_b = MSG_TALK_SUPPORT_151,
		.msg_talk_a = MSG_TALK_SUPPORT_152,
	},
	{
		.pid_a = PID_LUGH,
		.pid_b = PID_HUGH,
		.msg_talk_c = MSG_TALK_SUPPORT_153,
		.msg_talk_b = MSG_TALK_SUPPORT_154,
		.msg_talk_a = MSG_TALK_SUPPORT_155,
	},
	{
		.pid_a = PID_LUGH,
		.pid_b = PID_MELADY,
		.msg_talk_c = MSG_TALK_SUPPORT_156,
		.msg_talk_b = MSG_TALK_SUPPORT_157,
		.msg_talk_a = MSG_TALK_SUPPORT_158,
	},
	{
		.pid_a = PID_LILINA,
		.pid_b = PID_GONZALEZ,
		.msg_talk_c = MSG_TALK_SUPPORT_159,
		.msg_talk_b = MSG_TALK_SUPPORT_15A,
		.msg_talk_a = MSG_TALK_SUPPORT_15B,
	},
	{
		.pid_a = PID_HUGH,
		.pid_b = PID_NIIME,
		.msg_talk_c = MSG_TALK_SUPPORT_15C,
		.msg_talk_b = MSG_TALK_SUPPORT_15D,
		.msg_talk_a = MSG_TALK_SUPPORT_15E,
	},
	{
		.pid_a = PID_HUGH,
		.pid_b = PID_RAIGH,
		.msg_talk_c = MSG_TALK_SUPPORT_15F,
		.msg_talk_b = MSG_TALK_SUPPORT_160,
		.msg_talk_a = MSG_TALK_SUPPORT_161,
	},
	{
		.pid_a = PID_HUGH,
		.pid_b = PID_CATH,
		.msg_talk_c = MSG_TALK_SUPPORT_162,
		.msg_talk_b = MSG_TALK_SUPPORT_163,
		.msg_talk_a = MSG_TALK_SUPPORT_164,
	},
	{
		.pid_a = PID_NIIME,
		.pid_b = PID_RAIGH,
		.msg_talk_c = MSG_TALK_SUPPORT_165,
		.msg_talk_b = MSG_TALK_SUPPORT_166,
		.msg_talk_a = MSG_TALK_SUPPORT_167,
	},
	{
		.pid_a = PID_NIIME,
		.pid_b = PID_SOPHIA,
		.msg_talk_c = MSG_TALK_SUPPORT_168,
		.msg_talk_b = MSG_TALK_SUPPORT_169,
		.msg_talk_a = MSG_TALK_SUPPORT_16A,
	},
	{
		.pid_a = PID_RAIGH,
		.pid_b = PID_SOPHIA,
		.msg_talk_c = MSG_TALK_SUPPORT_16B,
		.msg_talk_b = MSG_TALK_SUPPORT_16C,
		.msg_talk_a = MSG_TALK_SUPPORT_16D,
	},
	{
		.pid_a = PID_LARUM,
		.pid_b = PID_ECHIDNA,
		.msg_talk_c = MSG_TALK_SUPPORT_16E,
		.msg_talk_b = MSG_TALK_SUPPORT_16F,
		.msg_talk_a = MSG_TALK_SUPPORT_170,
	},
	{
		.pid_a = PID_LARUM,
		.pid_b = PID_GEESE,
		.msg_talk_c = MSG_TALK_SUPPORT_171,
		.msg_talk_b = MSG_TALK_SUPPORT_172,
		.msg_talk_a = MSG_TALK_SUPPORT_173,
	},
	{
		.pid_a = PID_JUNO,
		.pid_b = PID_THEA,
		.msg_talk_c = MSG_TALK_SUPPORT_174,
		.msg_talk_b = MSG_TALK_SUPPORT_175,
		.msg_talk_a = MSG_TALK_SUPPORT_176,
	},
	{
		.pid_a = PID_JUNO,
		.pid_b = PID_SHANNA,
		.msg_talk_c = MSG_TALK_SUPPORT_177,
		.msg_talk_b = MSG_TALK_SUPPORT_178,
		.msg_talk_a = MSG_TALK_SUPPORT_179,
	},
	{
		.pid_a = PID_JUNO,
		.pid_b = PID_ZELOT,
		.msg_talk_c = MSG_TALK_SUPPORT_17A,
		.msg_talk_b = MSG_TALK_SUPPORT_17B,
		.msg_talk_a = MSG_TALK_SUPPORT_17C,
	},
	{
		.pid_a = PID_JUNO,
		.pid_b = PID_TREC,
		.msg_talk_c = MSG_TALK_SUPPORT_17D,
		.msg_talk_b = MSG_TALK_SUPPORT_17E,
		.msg_talk_a = MSG_TALK_SUPPORT_17F,
	},
	{
		.pid_a = PID_JUNO,
		.pid_b = PID_NOAH,
		.msg_talk_c = MSG_TALK_SUPPORT_180,
		.msg_talk_b = MSG_TALK_SUPPORT_181,
		.msg_talk_a = MSG_TALK_SUPPORT_182,
	},
	{
		.pid_a = PID_THEA,
		.pid_b = PID_SHANNA,
		.msg_talk_c = MSG_TALK_SUPPORT_183,
		.msg_talk_b = MSG_TALK_SUPPORT_184,
		.msg_talk_a = MSG_TALK_SUPPORT_185,
	},
	{
		.pid_a = PID_THEA,
		.pid_b = PID_ZELOT,
		.msg_talk_c = MSG_TALK_SUPPORT_186,
		.msg_talk_b = MSG_TALK_SUPPORT_187,
		.msg_talk_a = MSG_TALK_SUPPORT_188,
	},
	{
		.pid_a = PID_SHANNA,
		.pid_b = PID_ZELOT,
		.msg_talk_c = MSG_TALK_SUPPORT_189,
		.msg_talk_b = MSG_TALK_SUPPORT_18A,
		.msg_talk_a = MSG_TALK_SUPPORT_18B,
	},
	{
		.pid_a = PID_ZEISS,
		.pid_b = PID_MELADY,
		.msg_talk_c = MSG_TALK_SUPPORT_18C,
		.msg_talk_b = MSG_TALK_SUPPORT_18D,
		.msg_talk_a = MSG_TALK_SUPPORT_18E,
	},
	{
		.pid_a = PID_ELFFIN,
		.pid_b = PID_CECILIA,
		.msg_talk_c = MSG_TALK_SUPPORT_18F,
		.msg_talk_b = MSG_TALK_SUPPORT_190,
		.msg_talk_a = MSG_TALK_SUPPORT_191,
	},
	{
		.pid_a = PID_CATH,
		.pid_b = PID_GEESE,
		.msg_talk_c = MSG_TALK_SUPPORT_192,
		.msg_talk_b = MSG_TALK_SUPPORT_193,
		.msg_talk_a = MSG_TALK_SUPPORT_194,
	},
	{
		.pid_a = PID_MELADY,
		.pid_b = PID_TREC,
		.msg_talk_c = MSG_TALK_SUPPORT_195,
		.msg_talk_b = MSG_TALK_SUPPORT_196,
		.msg_talk_a = MSG_TALK_SUPPORT_197,
	},
	{
		.pid_a = PID_GONZALEZ,
		.pid_b = PID_ECHIDNA,
		.msg_talk_c = MSG_TALK_SUPPORT_198,
		.msg_talk_b = MSG_TALK_SUPPORT_199,
		.msg_talk_a = MSG_TALK_SUPPORT_19A,
	},
	{
		.pid_a = PID_GONZALEZ,
		.pid_b = PID_TREC,
		.msg_talk_c = MSG_TALK_SUPPORT_19B,
		.msg_talk_b = MSG_TALK_SUPPORT_19C,
		.msg_talk_a = MSG_TALK_SUPPORT_19D,
	},
	{
		.pid_a = PID_NOAH,
		.pid_b = PID_ZELOT,
		.msg_talk_c = MSG_TALK_SUPPORT_19E,
		.msg_talk_b = MSG_TALK_SUPPORT_19F,
		.msg_talk_a = MSG_TALK_SUPPORT_1A0,
	},
	{
		.pid_a = PID_NOAH,
		.pid_b = PID_TREC,
		.msg_talk_c = MSG_TALK_SUPPORT_1A1,
		.msg_talk_b = MSG_TALK_SUPPORT_1A2,
		.msg_talk_a = MSG_TALK_SUPPORT_1A3,
	},
	{
		.pid_a = PID_TREC,
		.pid_b = PID_ZELOT,
		.msg_talk_c = MSG_TALK_SUPPORT_1A4,
		.msg_talk_b = MSG_TALK_SUPPORT_1A5,
		.msg_talk_a = MSG_TALK_SUPPORT_1A6,
	},
	{
		.pid_a = PID_ECHIDNA,
		.pid_b = PID_GEESE,
		.msg_talk_c = MSG_TALK_SUPPORT_1A7,
		.msg_talk_b = MSG_TALK_SUPPORT_1A8,
		.msg_talk_a = MSG_TALK_SUPPORT_1A9,
	},
	{
		.pid_a = PID_LILINA,
		.pid_b = PID_CECILIA,
		.msg_talk_c = MSG_TALK_SUPPORT_1AA,
		.msg_talk_b = MSG_TALK_SUPPORT_1AB,
		.msg_talk_a = MSG_TALK_SUPPORT_1AC,
	},
	{}
};

u8 eventinfo_data_align[0x667640 - 0x6675F8] = {};
